import { SymbolGlyphModifier } from "@ohos.arkui.modifier"
import { scanCore, scanBarcode } from '@kit.ScanKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { BusinessError, systemDateTime } from '@kit.BasicServicesKit';
import { cryptoFramework } from '@kit.CryptoArchitectureKit';
import { Setting } from './Setting';
import { userAuth } from '@kit.UserAuthenticationKit';
import { Detail } from './Detail';
import { AuthData, AuthDataStore, DefaultToastDuration, PromptParams, SteamAccountData } from './Base';
import { SteamConfirmationList } from './SteamConfirmationList';
import { SteamConfirmationDetail } from './SteamConfirmationDetail';
import { Confirmation } from './Steam';
import { Add, AddSecret, AddSteamSecret, AddUri } from "./Add";
import {
  AddSteamToken,
  SteamConfirmLink,
  SteamConfirmTransferAuthenticator,
  SteamLink,
  SteamLogin,
  SteamMFALogin,
  SteamTransferAuthenticator,
  SteamRefreshToken
} from "./AddSteam";
import { ShowPrivacyView } from "./PrivacyView";
import { curves } from "@kit.ArkUI";

@Entry
@Component
struct Index {
  @State items: AuthData[] = [];
  dragIndex: number = -1;
  @State dragItem?: AuthData = undefined;
  @State showTokens: Record<number, boolean> = [];
  @State progress: number = 0;
  @Provide("pageStack") pageStack: NavPathStack = new NavPathStack();
  @Provide("authDataStore") authDataStore: AuthDataStore = new AuthDataStore((items) => {
    this.items = items
  })
  @Provide("safe") safe: boolean = false;
  @StorageProp("enableSafeMode") enableSafeMode: boolean = false
  @StorageProp("hideToken") hideToken: boolean = false
  @StorageLink("privacyState") privacyState: string = "Unknown"
  private timer?: number;

  aboutToAppear(): void {
    this.items = this.authDataStore.items
    this.progress = systemDateTime.getTime(false) / 1000 % 30
    this.timer = setInterval(() => {
      this.progress = systemDateTime.getTime(false) / 1000 % 30
      this.authDataStore.refreshAllPassword()
    }, 1000)

    if (this.privacyState == "Unknown") {
      ShowPrivacyView(this.getUIContext(), (state: string) => {
        this.privacyState = state
      })
    }

  }

  aboutToDisappear(): void {
    if (this.timer) {
      clearInterval(this.timer)
    }
  }

  isAvailableAuthType(authType: userAuth.UserAuthType, authLevel: userAuth.AuthTrustLevel): boolean {
    try {
      userAuth.getAvailableStatus(authType, authLevel);
      return true
    } catch (error) {
      const err: BusinessError = error as BusinessError;
      hilog.error(0x0001, '[Auth Sample]',
        `Current auth trust level [${authType}/${authLevel}] is not supported. Code is ${err?.code}, message is ${err?.message}`);
    }
    return false
  }

  unlock(): void {
    // 获取认证状态
    if (!this.isAvailableAuthType(userAuth.UserAuthType.PIN, userAuth.AuthTrustLevel.ATL3) &&
      !this.isAvailableAuthType(userAuth.UserAuthType.FINGERPRINT, userAuth.AuthTrustLevel.ATL3) &&
      !this.isAvailableAuthType(userAuth.UserAuthType.FACE, userAuth.AuthTrustLevel.ATL3)) {
      this.safe = true
      return
    }
    this.onPageShow()
  }

  onPageShow(): void {
    if (!this.enableSafeMode) {
      this.safe = true
      return
    }
    // 设置认证参数
    try {
      const rand = cryptoFramework.createRandom();
      const len: number = 16;
      const randData: Uint8Array = rand?.generateRandomSync(len)?.data;
      const authParam: userAuth.AuthParam = {
        challenge: randData,
        authType: [userAuth.UserAuthType.FACE, userAuth.UserAuthType.FINGERPRINT, userAuth.UserAuthType.PIN],
        authTrustLevel: userAuth.AuthTrustLevel.ATL3,
      };
      // 配置认证界面
      const widgetParam: userAuth.WidgetParam = {
        title: '请进行身份认证',
      };
      // 获取认证对象
      const userAuthInstance = userAuth.getUserAuthInstance(authParam, widgetParam);
      // 订阅认证结果
      let self = this
      userAuthInstance.on('result', {
        onResult(result) {
          // 可在认证结束或其他业务需要场景，取消订阅认证结果
          userAuthInstance.off('result');
          if (result.result == userAuth.UserAuthResultCode.SUCCESS) {
            self.safe = true
          } else {
            hilog.error(0x0001, '[Auth Sample]', `Failed to auth. Result: ${result.result}`);
          }
        }
      });
      userAuthInstance.start();
    } catch (error) {
      hilog.error(0x0001, '[Auth Sample]',
        `Failed to auth. Code: ${error.code}, message: ${error.message}`);
    }
  }

  onPageHide(): void {
    this.safe = false
  }

  @Builder
  PagesMap(name: string, param: object) {
    if (name == 'Add') {
      Add()
    } else if (name == "AddUri") {
      AddUri()
    } else if (name == "AddSecret") {
      AddSecret()
    } else if (name == "AddSteamToken") {
      AddSteamToken()
    } else if (name == "SteamLogin") {
      SteamLogin()
    } else if (name == "SteamMFALogin") {
      SteamMFALogin({ accountData: param as SteamAccountData })
    } else if (name == "SteamLink") {
      SteamLink({ accountData: param as SteamAccountData })
    } else if (name == "SteamConfirmLink") {
      SteamConfirmLink({ accountData: param as SteamAccountData })
    } else if (name == "SteamTransferAuthenticator") {
      SteamTransferAuthenticator({ accountData: param as SteamAccountData })
    } else if (name == "SteamConfirmTransferAuthenticator") {
      SteamConfirmTransferAuthenticator({ accountData: param as SteamAccountData })
    } else if (name == 'Setting') {
      Setting()
    } else if (name == 'Detail') {
      Detail({ item: param as AuthData })
    } else if (name == "SteamConfirmationList") {
      SteamConfirmationList({ steamAuthData: param["authData"], steamClient: param["client"] })
    } else if (name == "SteamConfirmationDetail") {
      SteamConfirmationDetail({ confirmation: param as Confirmation })
    } else if (name == "SteamRefreshToken") {
      SteamRefreshToken({ authData: param["baseAuthData"], steamAuthData: param["authData"] })
    } else if (name == "AddSteamSecret") {
      AddSteamSecret()
    }
  }

  private vendors: Map<string, string>= new Map([
    ["google", "Google.png"],
    ["microsoft", "Microsoft.png"],
    ["github", "Github.png"],
    ["gitlab", "Gitlab.png"],
    ["steam", "Steam.png"],
    ["huawei", "Huawei.png"],
    ["aliyun", "Aliyun.png"],
    ["namecheap", "Namecheap.png"],
    ["neteasemail", "NeteaseMail.png"],
    ["nintendo", "Nintendo.png"],
    ["nintendo account", "Nintendo.png"],
    ["epic games", "Epic Games.png"],
    ["cloudflare", "Cloudflare.png"],
    ["twitter", "Twitter.png"],
    ["nvidia", "Nvidia.png"],
    ["ubisoft", "Ubisoft.png"],
    ["uplay", "Ubisoft.png"],
    ["jetbrains", "Jetbrains.png"],
  ]);

  @Builder
  Logo(issuer: string) {
    if (this.vendors.has(issuer.toLowerCase())) {
      Image($rawfile(this.vendors.get(issuer.toLowerCase())))
        .width(40)
        .padding(5)
        .margin(10)
        .backgroundColor($r("app.color.vendor_background_color"))
        .borderRadius(20)
        .draggable(false)
    } else {
      SymbolGlyph($r("sys.symbol.person"))
        .fontSize(30)
        .padding(5)
        .margin(10)
        .fontColor([$r("app.color.vendor_icon_color")])
        .backgroundColor($r("app.color.vendor_background_color"))
        .borderRadius(20)
    }
  }

  build() {
    Column() {
      Navigation(this.pageStack) {
        if (this.items.length <= 0) {
          RelativeContainer() {
            Column() {
              SymbolGlyph($r("sys.symbol.info_shield"))
                .fontSize(35)
              Text("还没有添加过令牌密钥\n请点击右上角的加号或扫码按钮添加")
                .fontWeight(FontWeight.Bold)
                .padding(20)
                .textAlign(TextAlign.Center)
                .lineHeight(40)
            }
            .alignRules({
              center: { anchor: "__container__", align: VerticalAlign.Center },
              middle: { anchor: "__container__", align: HorizontalAlign.Center },
            })
          }
        } else {
          Progress({ value: this.progress, total: 29, type: ProgressType.Linear })
            .width("100%").height(5)
          List() {
            ForEach(this.items, (item: AuthData, index: number) => {
              ListItem() {
                Row() {
                  this.Logo(item.issuer)
                  Column() {
                    Text(item.alias)
                      .fontSize(20)
                      .fontWeight(FontWeight.Bold)
                    Text(this.safe ? item.account : "******")
                      .fontSize(10)
                  }
                  .alignItems(HorizontalAlign.Start)
                  .width("55%")

                  Text((this.safe && (!this.hideToken || this.showTokens[item.id])) ? item.password : "******")
                    .fontSize(20)
                    .fontWeight(FontWeight.Bold)
                    .onClick(() => {
                      if (!this.safe) {
                        this.getUIContext().getPromptAction().showToast({
                          duration: DefaultToastDuration,
                          message: "已启用安全模式，请先解锁"
                        })
                        return
                      }
                      if (!this.hideToken) {
                        this.pageStack.pushPathByName("Detail", item)
                        return
                      }
                      this.showTokens[item.id] = !!!this.showTokens[item.id]
                    })
                }
                .width("100%")
                .opacity(item.id == this.dragItem?.id ? 0 : 1)
                .onClick(() => {
                  if (!this.safe) {
                    this.getUIContext().getPromptAction().showToast({
                      duration: DefaultToastDuration,
                      message: "已启用安全模式，请先解锁"
                    })
                    return
                  }
                  this.pageStack.pushPathByName("Detail", item)
                })
              }
              .swipeAction({ end: this.deleteButton(item.id) })
              .borderColor($r("app.color.item_separator_color"))
              .borderWidth({ bottom: 1 })
              .onDragStart((event?: DragEvent, extraParams?: string) => {
                hilog.debug(0, "testa", `drag start: ${item.id}`)
                this.dragIndex = index
                this.dragItem = item
              })
              .onDragEnter((event?: DragEvent, extraParams?: string) => {
                if (!this.dragItem) {
                  return
                }
                if (item.id == this.dragItem?.id) {
                  return
                }
                hilog.debug(0, "testa", `drag enter: ${item.id}`)
                let currentIndex = this.items.findIndex((element) => element.id == this.dragItem!.id)
                let targetIndex = this.items.findIndex((element) => element.id == item.id)
                this.getUIContext()?.animateTo({
                  curve: curves.interpolatingSpring(0, 1, 400, 38)
                }, () => {
                  this.items.splice(currentIndex, 1)
                  this.items.splice(targetIndex, 0, this.dragItem!)
                })
              })
              .onDrop((dragEvent: DragEvent) => {
                hilog.debug(0, "testa", `drop: ${item.id}`)
                this.dragItem = undefined
                this.authDataStore.replaceAuthItems(this.items)
              })
              .onDragEnd(() => {
                if (!this.dragItem) {
                  return
                }
                hilog.debug(0, "testa", `drag cancel: ${item.id}`)
                let currentIndex = this.items.findIndex((element) => element.id == this.dragItem!.id)
                this.getUIContext()?.animateTo({
                  curve: curves.interpolatingSpring(0, 1, 400, 38)
                }, () => {
                  this.items.splice(currentIndex, 1)
                  this.items.splice(this.dragIndex, 0, this.dragItem!)
                  this.dragItem = undefined
                })
              })
            }, (item: AuthData) => item.id.toString() + "-" + item.alias + "-" + item.account + "-" + item.password)
          }
        }
      }
      .navDestination(this.PagesMap)
      .menus(this.safe ? [
        {
          value: "add",
          symbolIcon: new SymbolGlyphModifier($r('sys.symbol.plus')),
          action: () => this.onAddButtonPressed()
        },
        {
          value: "scan",
          symbolIcon: new SymbolGlyphModifier($r('sys.symbol.line_viewfinder')),
          action: () => this.onScanButtonPressed()
        },
        {
          value: "setting",
          symbolIcon: new SymbolGlyphModifier($r('sys.symbol.gearshape')),
          action: () => {
            if (!this.safe) {
              this.getUIContext().getPromptAction().showToast({
                duration: DefaultToastDuration,
                message: "已启用安全模式，请先解锁"
              })
              return
            }
            this.pageStack.pushPathByName("Setting", undefined)
          }
        },
      ] : [
        {
          value: "unlock",
          symbolIcon: new SymbolGlyphModifier($r('sys.symbol.lock')),
          action: () => this.unlock()
        },
      ])
      .title($r("app.string.EntryAbility_label"))
      .titleMode(NavigationTitleMode.Mini)
      .hideBackButton(true)
      .mode(NavigationMode.Auto)
    }
  }

  @Builder
  deleteButton(id: number) {
    Button() {
      SymbolGlyph($r("sys.symbol.trash"))
        .fontSize(35)
        .fontColor([$r("app.color.item_delete_icon_color")])
    }
    .backgroundColor($r("app.color.item_delete_background_color"))
    .type(ButtonType.Normal)
    .width(60)
    .height("100%")
    .onClick((event) => {
      if (!this.safe) {
        this.getUIContext().getPromptAction().showToast({
          duration: DefaultToastDuration,
          message: "已启用安全模式，请先解锁"
        })
        return
      }
      this.authDataStore.removeAuthItem(id)
      this.items = this.authDataStore.items
    })
  }

  onAddButtonPressed() {
    if (!this.safe) {
      this.getUIContext().getPromptAction().showToast({
        duration: DefaultToastDuration,
        message: "已启用安全模式，请先解锁"
      })
      return
    }
    this.pageStack.pushPathByName("Add", undefined)
  }

  onScanButtonPressed() {
    if (!this.safe) {
      this.getUIContext().getPromptAction().showToast({
        duration: DefaultToastDuration,
        message: "已启用安全模式，请先解锁"
      })
      return
    }
    let options: scanBarcode.ScanOptions =
      { scanTypes: [scanCore.ScanType.ALL], enableMultiMode: true, enableAlbum: true };
    try {
      scanBarcode.startScanForResult(getContext(this), options).then((result: scanBarcode.ScanResult) => {
        try {
          if (result.originalValue.startsWith("https://s.team/q/")) {
            this.loginSteam(result.originalValue)
            return
          }
          this.authDataStore.addAuthItem(result.originalValue)
          this.getUIContext().getPromptAction().showToast({
            duration: DefaultToastDuration,
            message: "成功添加令牌"
          })
        } catch (error) {
          this.getUIContext().getPromptAction().showToast({
            duration: DefaultToastDuration,
            message: `扫码失败：${error}`
          })
        }
      })
    } catch (error) {
      this.getUIContext().getPromptAction().showToast({
        duration: DefaultToastDuration,
        message: `扫码失败：${error}`
      })
    }
  }

  loginSteam(url: String) {
    let steamTokenCount = 0;
    let steamAuthDataCount = 0;
    for (let i = 0; i < this.items.length; i++) {
      let item = this.items[i]
      if (item.issuer == "Steam") {
        steamTokenCount++
        if (item.external != "") {
          steamAuthDataCount++
        }
      }
    }
    if (steamTokenCount <= 0) {
      this.getUIContext().getPromptAction().showToast({
        duration: DefaultToastDuration,
        message: "没有 Steam 令牌，无法扫码登陆 Steam，请先添加 Steam 令牌"
      })
      return
    }
    if (steamAuthDataCount <= 0) {
      this.getUIContext().getPromptAction().showToast({
        duration: DefaultToastDuration,
        message: "Steam 令牌没有设置认证信息，无法扫码登陆 Steam，请在令牌详情页设置"
      })
      return
    }
    this.getUIContext().getPromptAction().showToast({
      duration: DefaultToastDuration,
      message: "请在 Steam 令牌详情页扫码登陆"
    })
    return
  }
}